In [ ]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic operations like:     
a) Addition of 2 in all the element     
b) Multiply 3 with all the elements  
c) Divide every element by 2

In [ ]:
a = np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Q.2 Questions on Basic NumPy Array:     
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])    
b) Find the most frequent value and their indice(s) in the following arrays:  
i. x = np.array([1,2,3,4,5,1,2,1,1,1])       
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [ ]:
x = np.array([1,2,3,4,5,1,2,1,1,1])
most_frequent= np.bincount(x).argmax()
indices = np.where(x==most_frequent)[0]
print(indices, most_frequent)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_frequent_y = np.bincount(x).argmax()
indices_y = np.where(x==most_frequent)[0]
print(indices_y, most_frequent_y)

[0 5 7 8 9] 1
[0 5 7 8 9] 1


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access elements using row and column indices as follows:        
 a) Access 1st row, 2nd column              
  b) Access 3rd row, 1st column

In [ ]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])

print(arr1[0][1])

print(arr1[2][0])

20
70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array, shape, total elements, the data type of each element and total number of bytes consumed by the array. Find the transpose of this array using reshape() attribute. Can we do the same with T attribute?

In [ ]:
Piyush = np.linspace(10, 100, 25)


print(Piyush)
print(Piyush.ndim)
print(Piyush.shape)
print(Piyush.size)
print(Piyush.dtype)
print(Piyush.nbytes)


transpose_array = Piyush.reshape(25, 1)
print(transpose_array)

transpose_T = Piyush.T
print(transpose_T)


[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>> with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean, median, max, min, unique elements. Reshape the array to four rows and three columns and name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three columns and name it as resized_ ucs420_<your_name>>.

In [ ]:
ucs420_Piyush = np.array([[ 10, 20, 30, 40],[50, 60, 70, 80],[90, 15, 20, 35]])
ucs420_Piyush_mean = np.mean(ucs420_Piyush)
print(ucs420_Piyush_mean)
ucs420_Piyush_median = np.median(ucs420_Piyush)
print(ucs420_Piyush_median)
print(np.max(ucs420_Piyush))
print(np.min(ucs420_Piyush))
print(np.unique(ucs420_Piyush))
reshaped_ucs420_Piyush = np.reshape(ucs420_Piyush, (4,3))
resized_ucs420_Piyush = np.resize(ucs420_Piyush, (2,3))
print(reshaped_ucs420_Piyush)
print(resized_ucs420_Piyush)


43.333333333333336
37.5
90
10
[10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
